[project]
name = 'stacks-medchain-immunity-nexus'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.healthcare-provider-registry]
path = 'contracts/healthcare-provider-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.immunity-passport-registry]
path = 'contracts/immunity-passport-registry.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
